# 特征值和特征向量

In [2]:
import tensorflow as tf
import numpy as np

# 构建矩阵
m = np.array([1, 2, 3, 4]).reshape(2, 2)
print(m)

# 求特征值和特征向量
t = tf.self_adjoint_eig(m.astype("float32"))

with tf.Session() as sess:
    print(sess.run(t))

[[1 2]
 [3 4]]
(array([-0.85410208,  5.85410213], dtype=float32), array([[-0.85065085, -0.52573109],
       [ 0.52573109, -0.85065085]], dtype=float32))


# 目录遍历

In [29]:
import os

dataset_path = './test'

# 遍历dataset_path文件夹
# 其中f[0]代表该文件夹路径名，f[1]代表文件夹内的文件夹列表，f[2]代表文件夹内文件列表
f = os.walk(dataset_path).__next__()[1]
print(f)

# 一般对多个文件/夹进行排序
f = sorted(f)
print(f)

# 二级目录
for fs in f:
    print('--------------------------------')
    fs_dir = os.path.join(dataset_path, fs)
    fs = os.walk(fs_dir).__next__()
    # 输出fs文件夹内的所有内容，即三个大小的元组
    print(fs)

['.ipynb_checkpoints', 't1', 't2']
['.ipynb_checkpoints', 't1', 't2']
--------------------------------
('./test/.ipynb_checkpoints', [], [])
--------------------------------
('./test/t1', ['Untitled Folder 1', 'Untitled Folder'], ['untitled1.txt', 'untitled.txt', 'untitled2.txt'])
--------------------------------
('./test/t2', [], ['untitled.txt'])


# dataset中shuffle()、repeat()、batch()用法

In [2]:
import numpy as np
import tensorflow as tf

np.random.seed(0)
x = np.random.sample((11,2))

# make a dataset from a numpy array
print(x)

[[ 0.5488135   0.71518937]
 [ 0.60276338  0.54488318]
 [ 0.4236548   0.64589411]
 [ 0.43758721  0.891773  ]
 [ 0.96366276  0.38344152]
 [ 0.79172504  0.52889492]
 [ 0.56804456  0.92559664]
 [ 0.07103606  0.0871293 ]
 [ 0.0202184   0.83261985]
 [ 0.77815675  0.87001215]
 [ 0.97861834  0.79915856]]


In [3]:
dataset = tf.data.Dataset.from_tensor_slices(x)
dataset = dataset.shuffle(2) # 将数据打乱，数值越大，混乱程度越大
dataset = dataset.batch(4) # 按照顺序取出4行数据，最后一次输出可能小于batch

dataset = dataset.repeat() # 数据集重复了指定次数
# repeat()在batch操作输出完毕后再执行,若在之前，相当于先把整个数据集复制两次
# 为了配合输出次数，一般默认repeat()空

# create the iterator
el = dataset.make_one_shot_iterator().get_next()

with tf.Session() as sess:
    for i in range(6):
        value = sess.run(el)
        print(value)

[[ 0.5488135   0.71518937]
 [ 0.4236548   0.64589411]
 [ 0.60276338  0.54488318]
 [ 0.43758721  0.891773  ]]
[[ 0.79172504  0.52889492]
 [ 0.56804456  0.92559664]
 [ 0.96366276  0.38344152]
 [ 0.0202184   0.83261985]]
[[ 0.77815675  0.87001215]
 [ 0.07103606  0.0871293 ]
 [ 0.97861834  0.79915856]]
[[ 0.5488135   0.71518937]
 [ 0.60276338  0.54488318]
 [ 0.4236548   0.64589411]
 [ 0.96366276  0.38344152]]
[[ 0.43758721  0.891773  ]
 [ 0.56804456  0.92559664]
 [ 0.07103606  0.0871293 ]
 [ 0.0202184   0.83261985]]
[[ 0.79172504  0.52889492]
 [ 0.77815675  0.87001215]
 [ 0.97861834  0.79915856]]
